let useTheme = () => Jotai.Atom.use(Atoms.themeAtom)
let useAccounts = () => Jotai.Atom.use(Atoms.accountsAtom)
let useSelectedAccount = () => Jotai.Atom.use(Atoms.selectedAccountAtom)
let useContacts = () => Jotai.Atom.use(Atoms.contactsAtom)
let useNetwork = () => Jotai.Atom.use(Atoms.networkAtom)
let useNodeIndex = () => Jotai.Atom.use(Atoms.nodeIndexAtom)
let useAddressMetadatas = () => Jotai.Atom.use(Atoms.addressMetatdadaAtom)
let useBiometricsEnabled = () => Jotai.Atom.use(Atoms.biometricsEnabledAtom)
